[build]
  publish = "dist"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080
